# this_file: src/lmstrix/api/helptext.py

from rich.console import Console

console = Console()


def show_help_command() -> None:
    console.print("[bold cyan]LMStrix - LM Studio Model Testing Toolkit[/bold cyan]")
    console.print("\n[cyan]Available commands:[/cyan]")
    console.print("  [green]scan[/green]            Scan for LM Studio models and update registry")
    console.print("    --failed          Re-scan only previously failed models")
    console.print("    --reset           Re-scan all models (clear test data)")
    console.print("    --verbose         Enable verbose output")
    console.print("")
    console.print("  [green]list[/green]            List all models with their test status")
    console.print(
        "    --sort id|ctx|dtx|size|smart  Sort by: id, tested context, declared context, size, smart"
    )
    console.print(
        "    --sort arch|inp|outp|proc     Sort by keyword category (add 'd' for descending)"
    )
    console.print("    --show id|path|json|md  Output format (md = Markdown report)")
    console.print("    --key kw1,kw2         Filter models matching all specified keywords")
    console.print("    --verbose         Enable verbose output")
    console.print("")
    console.print("  [green]desc[/green]            Generate model descriptions and keywords")
    console.print("    MODEL_ID          Describe specific model")
    console.print("    --all             Describe all undescribed models")
    console.print("    --model MODEL_ID  LLM to use (default: droid exec)")
    console.print("    --search 0|1|2    Web search before describing (0=off, 1=web-search, 2=ddg-search)")
    console.print("    --reset           Re-describe already described models")
    console.print("    --verbose         Enable verbose output")
    console.print("")
    console.print("  [green]test[/green]            Test model context limits")
    console.print("    MODEL_ID          Test specific model")
    console.print("    --all             Test all untested models")
    console.print("    --reset           Re-test all models")
    console.print("    --ctx SIZE        Test specific context size")
    console.print("    --threshold SIZE  Max context for initial testing (default: 31744)")
    console.print(
        "    --fast            Skip semantic verification (only test if inference completes)"
    )
    console.print("    --key kw1,kw2         Filter models matching all specified keywords")
    console.print("    --prompt TEXT     Custom prompt to use for testing")
    console.print("    --file_prompt PATH Load prompt from file for testing")
    console.print("    --verbose         Enable verbose output")
    console.print("")
    console.print("  [green]infer[/green]           Run inference on a model")
    console.print("    PROMPT MODEL_ID   Required prompt and model")
    console.print("    --out_ctx NUM|%   Maximum tokens to generate (e.g., 500 or '80%')")
    console.print("    --in_ctx NUM      Context size for loading model")
    console.print("    --file_prompt PATH Load prompt from TOML file")
    console.print("    --dict PARAMS     Parameters as key=value pairs")
    console.print("    --temperature NUM Temperature for generation")
    console.print("    --reload          Force reload model")
    console.print("    --verbose         Enable verbose output")
    console.print("")
    console.print("  [green]doctor[/green]          Check database health and backups")
    console.print("    --verbose         Show detailed health information")
    console.print("")
    console.print("  [green]about[/green]           Show general information about LMStrix")
    console.print("    --verbose         Show detailed information")
    console.print("")
    console.print("  [green]save[/green]            Save tested contexts to LM Studio configs")
    console.print("    --flash           Enable flash attention for GGUF models")
    console.print(
        "    --limit NUM|%     Context limit - percentage (e.g. '50%') or absolute (e.g. 4096)"
    )
    console.print("                      With %: applies to contexts > threshold")
    console.print("                      Without %: sets min(tested_context, limit) for all")
    console.print("    --threshold NUM   With % limit: apply percentage if context > threshold")
    console.print("    --verbose         Enable verbose output")
    console.print("")
    console.print("Examples:")
    console.print("  lmstrix scan --verbose")
    console.print("  lmstrix list --sort ctx")
    console.print("  lmstrix list --show md --key outp-code,proc-thinking")
    console.print("  lmstrix list --sort arch --show md")
    console.print("  lmstrix desc --all                    # uses droid exec")
    console.print("  lmstrix desc --all --model my-llm      # uses LM Studio model")
    console.print("  lmstrix desc --all --search 2          # enrich with ddg-search")
    console.print("  lmstrix desc my-model --reset")
    console.print("  lmstrix test --all")
    console.print("  lmstrix test --all --key arch-gguf")
    console.print("  lmstrix test my-model --ctx 8192")
    console.print('  lmstrix test my-model --prompt "What is 2+2?"')
    console.print("  lmstrix test my-model --file_prompt test_prompt.txt")
    console.print('  lmstrix infer "Hello world" my-model')
    console.print("  lmstrix save --flash")
    console.print("  lmstrix save --limit 75 --threshold 20000")
    console.print("  lmstrix about")
