
theme: jekyll-theme-minimal
title: LMStrix
description: "The Unofficial Toolkit for Mastering LM Studio"
logo: /assets/img/logo.png
show_downloads: true
github:
  zip_url: https://github.com/twardoch/lmstrix/archive/main.zip
  tar_url: https://github.com/twardoch/lmstrix/archive/main.tar.gz
